function cifti_parcellation(wb_dir, input, label, output)
%%
% Written by Bocheng Wang 2020.05.28

wb_command = [ wb_dir    '  -cifti-parcellate ' ...
                             input      ' '                            ...
                             label                                      ...
                            ' COLUMN '                           ...
                            output                                   ...
                            ]; 
system(wb_command);
