function cifti_correlation(wb_dir, input, output)
%CIFTI_CORRECTION
%   Written by Bocheng Wang 2020.05.28
wb_command = [  wb_dir            ...
                                ' -cifti-correlation '    ...
                                input   ' '                   ...
                               output                         ...
                            ];
system(wb_command);
end

