# Generated by Django 3.2 on 2021-06-07 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DBCPOnline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Server_Name', models.CharField(max_length=50, null=True)),
                ('Server_IP', models.CharField(default='0.0.0.0', max_length=20)),
                ('Server_IsParcellation_and_CorrelationBusy', models.BooleanField(default=False)),
                ('Server_IsCausalityBusy', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TaskQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=50, null=True)),
                ('NeedThreading', models.BooleanField(default=True)),
                ('Description', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CorrelationConnectivityTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_Start', models.BooleanField(default=False)),
                ('Task_StartTime', models.DateTimeField(blank=True, null=True)),
                ('Task_Finish', models.BooleanField(default=False)),
                ('Task_EndTime', models.DateTimeField(blank=True, null=True)),
                ('Preprocess_Type', models.CharField(max_length=10, null=True)),
                ('Preprocessed_Dir', models.CharField(max_length=255, null=True)),
                ('AfterPreprocessed_Saved_Dir', models.CharField(max_length=255, null=True)),
                ('Progress_value', models.FloatField(default=0)),
                ('Task_Thread_ID', models.IntegerField(default=0)),
                ('Task_Status', models.IntegerField(default=200)),
                ('Task_Modal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DBCPOnline.modalinfo')),
                ('Task_Server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DBCP_Scheduler.server')),
            ],
        ),
        migrations.CreateModel(
            name='CausalityConnectivityTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_Start', models.BooleanField(default=False)),
                ('Task_StartTime', models.DateTimeField(blank=True, null=True)),
                ('Task_Finish', models.BooleanField(default=False)),
                ('Task_EndTime', models.DateTimeField(blank=True, null=True)),
                ('Task_Type', models.CharField(max_length=50, null=True)),
                ('Preprocessed_Dir', models.CharField(max_length=255, null=True)),
                ('AfterPreprocessed_Saved_Dir', models.CharField(max_length=255, null=True)),
                ('Progress_value', models.FloatField(default=0)),
                ('Task_Thread_ID', models.IntegerField(default=0)),
                ('Task_Status', models.IntegerField(default=200)),
                ('Task_Modal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DBCPOnline.modalinfo', unique=True)),
                ('Task_Server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DBCP_Scheduler.server')),
            ],
        ),
    ]
