# Generated by Django 3.2 on 2021-06-07 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBCP_Scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='Server_Type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
