# Generated by Django 3.2 on 2021-06-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBCP_Scheduler', '0003_remove_server_server_iscausalitybusy'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='Server_IsBusy',
            field=models.BooleanField(default=False),
        ),
    ]
