# Generated by Django 3.2 on 2021-06-07 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBCP_Scheduler', '0004_server_server_isbusy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='Server_IsParcellation_and_CorrelationBusy',
        ),
    ]
