# Generated by Django 3.2 on 2021-06-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBCP_Scheduler', '0005_remove_server_server_isparcellation_and_correlationbusy'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskqueue',
            name='isScheduled',
            field=models.BooleanField(default=True),
        ),
    ]
