# Generated by Django 3.2 on 2021-06-09 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBCPOnline', '0009_alter_modalinfo_uuidstr'),
        ('DBCP_Scheduler', '0007_remove_taskqueue_needthreading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causalityconnectivitytask',
            name='Task_Modal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DBCPOnline.modalinfo'),
        ),
    ]
