# Generated by Django 3.2 on 2021-06-13 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBCPOnline', '0010_alter_modalinfo_uuidstr'),
        ('DBCP_Scheduler', '0008_alter_causalityconnectivitytask_task_modal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causalityconnectivitytask',
            name='Task_Modal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DBCPOnline.modalinfo', unique=True),
        ),
    ]
