# Generated by Django 3.2 on 2021-06-13 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBCP_Scheduler', '0010_server_server_isdebug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='Server_IsDebug',
        ),
    ]
