# Generated by Django 3.2 on 2021-06-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBCP_Scheduler', '0011_remove_server_server_isdebug'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskqueue',
            name='isDebug',
            field=models.BooleanField(default=True),
        ),
    ]
