# Generated by Django 3.2 on 2021-06-13 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBCPOnline', '0014_alter_modalinfo_uuidstr'),
        ('DBCP_Scheduler', '0012_taskqueue_isdebug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causalityconnectivitytask',
            name='Task_Modal',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='DBCPOnline.modalinfo'),
        ),
    ]
