# Generated by Django 3.2 on 2021-06-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBCP_Scheduler', '0013_alter_causalityconnectivitytask_task_modal'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskqueue',
            name='Task_LastRunTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
