"""
Django settings for DBCP project.

Generated by 'django-admin startproject' using Django 3.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""
import logging
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*1)8t$s3p9a#%_ckiydl)-tywl7_qx1%$&hk9bwr64jex39@r$'

# 2022.03.31 capthca error temp
SILENCED_SYSTEM_CHECKS = ['captcha.recaptcha_test_key_error']
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'UserManagement.apps.UsermanagementConfig',
    'captcha',
    'ContentManagement.apps.ContentmanagementConfig',
    'DBCPOnline.apps.DbcponlineConfig',
    # 'TimingTask.apps.TimingtaskConfig',
    'KalmanFilter.apps.KalmanfilterConfig',
    'DBCP_Scheduler.apps.DbcpSchedulerConfig'
]

MIDDLEWARE = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DBCP.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
WSGI_APPLICATION = 'DBCP.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'DBCP',
        'USER': 'root',
        'PASSWORD': 'root',
        'ONN_MAX_AGE': 300,
        # 'HOST': '10.1.125.13',
        # 'HOST': '10.170.2.108',
        'HOST': '10.1.83.158',

        'OPTIONS': {
            "init_command": "SET GLOBAL max_connections = 100000,character_set_connection=utf8,collation_connection=utf8_unicode_ci",
            # <-- The fix
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },

    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LOCALE_PATHS = [os.path.join(BASE_DIR, 'locale'), ]
# LANGUAGE_CODE = 'zh-hans'
# LANGUAGE_CODE = 'zh-CN'
LANGUAGE_CODE = 'en-US'

TIME_ZONE = 'America/Chicago'
# TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True
USE_L10N = True
USE_TZ = True

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# email setting
EMAIL_USE_SSL = True
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtphz.qiye.163.com'
EMAIL_PORT = 994
EMAIL_HOST_USER = 'DBCP@cuz.edu.cn'
EMAIL_HOST_PASSWORD = 'DBCP.Online'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
CONFIRM_DAYS = 7

# session setting
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Custom setting
CUSTOM_SETTINGS = {
    'Domain': 'dbcp.cuz.edu.cn',
    'DBCP.Storage.Server': '10.1.125.6',
    'DBCP.Mysql.Server': '10.1.125.13',
    'DBCP.Web.Server': '10.1.125.7'
}

# AVAILABLE_DBCP_ONLINE_SERVER_IP = [
#     '10.1.125.8',
#     '10.1.125.9',
#     '10.1.125.10',
#     '10.1.125.11'
# ]


logging.basicConfig(level=logging.INFO,
                    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
                    filename='runserver.log')
