# Generated by Django 3.2 on 2021-06-07 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connectivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mode', models.CharField(choices=[('static', '静态'), ('dynamic', '动态')], max_length=10)),
                ('generate_time', models.DateTimeField(auto_now_add=True)),
                ('frameNumInDynamic', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectID', models.CharField(max_length=255, unique=True)),
                ('career', models.CharField(max_length=255)),
                ('education_years', models.IntegerField(default=0)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Visit_age', models.FloatField(default=0)),
                ('Phase', models.CharField(choices=[('BL', '基线随访'), ('SC', '观察阶段'), ('M03', '三月随访'), ('M06', '半年随访'), ('M12', '一年随访'), ('M24', '两年随访'), ('M36', '三年随访'), ('M48', '四年随访'), ('M60', '五年随访')], max_length=50)),
                ('Diagnosis', models.CharField(choices=[('Healthy Control', '健康对照'), ('Early MCI', '早期轻度认知障碍'), ('Late MCI', '晚期轻度认知障碍'), ('Alzheimer`s Disease', '阿尔兹海默症')], max_length=50)),
                ('visit_time', models.DateTimeField(blank=True, null=True)),
                ('MMSE', models.FloatField(default=0)),
                ('CDR', models.FloatField(default=0)),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBCPOnline.subject')),
            ],
        ),
        migrations.CreateModel(
            name='RARFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('filesize', models.IntegerField(default=0)),
                ('storage_path', models.CharField(max_length=255)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('isCheck', models.BooleanField(default=False)),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManagement.user')),
            ],
        ),
        migrations.CreateModel(
            name='ModalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuidStr', models.CharField(default='78cfb835-3ad0-4bc8-89e6-8f1aeacfd6b5', max_length=50)),
                ('modalName', models.CharField(choices=[('MRI', '磁共振'), ('DTI', '扩散张量成像'), ('Fieldmap', '场域信息')], max_length=50)),
                ('DataSource', models.CharField(choices=[('ADNI1', 'ADNI1'), ('ADNI2', 'ADNI2'), ('ADNI3', 'ADNI3'), ('ADNI_GO', 'ADNI_GO')], max_length=100)),
                ('OtherFilePath', models.CharField(max_length=255)),
                ('RARFile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DBCPOnline.rarfile')),
                ('Visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBCPOnline.visit')),
            ],
        ),
    ]
