# Generated by Django 3.2 on 2021-06-07 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBCPOnline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalinfo',
            name='uuidStr',
            field=models.CharField(default='863f9773-77d7-42fb-a5d2-27f28def95db', max_length=50),
        ),
    ]
