# Generated by Django 3.2 on 2021-06-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBCPOnline', '0002_alter_modalinfo_uuidstr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalinfo',
            name='uuidStr',
            field=models.CharField(default='32e8c0ea-802b-4829-aa3c-c5caffb2f0fe', max_length=50),
        ),
    ]
