# Generated by Django 3.2 on 2021-06-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBCPOnline', '0003_alter_modalinfo_uuidstr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalinfo',
            name='uuidStr',
            field=models.CharField(default='9ceda4bf-480e-46d4-b3d6-fc795327e37a', max_length=50),
        ),
    ]
