# Generated by Django 3.2 on 2021-06-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBCPOnline', '0005_alter_modalinfo_uuidstr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalinfo',
            name='uuidStr',
            field=models.CharField(default='ce6c82c3-bc59-4a63-bd1a-80f208a21f95', max_length=50),
        ),
    ]
