# Generated by Django 3.2 on 2021-06-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBCPOnline', '0006_alter_modalinfo_uuidstr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalinfo',
            name='uuidStr',
            field=models.CharField(default='e617e3ae-3ad9-48fd-99a9-83a823448335', max_length=50),
        ),
    ]
