# Generated by Django 3.2 on 2021-06-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBCPOnline', '0007_alter_modalinfo_uuidstr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalinfo',
            name='uuidStr',
            field=models.CharField(default='dd27e8d2-a6be-43d0-8e97-9b905c759877', max_length=50),
        ),
    ]
