# Generated by Django 3.2 on 2021-06-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBCPOnline', '0009_alter_modalinfo_uuidstr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalinfo',
            name='uuidStr',
            field=models.CharField(default='66cadd39-caac-40a8-96a7-3d92a8fa0c58', max_length=50),
        ),
    ]
