# Generated by Django 3.2 on 2021-06-13 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBCPOnline', '0010_alter_modalinfo_uuidstr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalinfo',
            name='uuidStr',
            field=models.CharField(default='1183527b-425f-4415-a194-6e8cc828d931', max_length=50),
        ),
    ]
