# Generated by Django 3.2 on 2021-06-13 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBCPOnline', '0011_alter_modalinfo_uuidstr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalinfo',
            name='uuidStr',
            field=models.CharField(default='04bb7131-f3c5-489d-97ad-c5cd6e6707bb', max_length=50),
        ),
    ]
