# Generated by Django 3.2 on 2021-06-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBCPOnline', '0012_alter_modalinfo_uuidstr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalinfo',
            name='uuidStr',
            field=models.CharField(default='86164b0a-d9e7-41b9-a42a-6c04ad15ae7e', max_length=50),
        ),
    ]
