# Generated by Django 3.2 on 2021-07-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBCPOnline', '0015_alter_modalinfo_uuidstr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalinfo',
            name='uuidStr',
            field=models.CharField(default='5d65653e-b1ce-449c-9684-30fe9ec02939', max_length=50),
        ),
    ]
