# Generated by Django 3.2 on 2021-10-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBCPOnline', '0016_alter_modalinfo_uuidstr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalinfo',
            name='uuidStr',
            field=models.CharField(default='cc3d4ae7-2b97-4538-9448-95f440d95f3e', max_length=50),
        ),
    ]
