# Generated by Django 3.2 on 2021-10-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBCPOnline', '0017_alter_modalinfo_uuidstr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalinfo',
            name='uuidStr',
            field=models.CharField(default='cb3cd8d9-7036-425e-9eae-0a1d88e500ba', max_length=50),
        ),
    ]
