# Generated by Django 3.2 on 2021-10-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBCPOnline', '0018_alter_modalinfo_uuidstr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalinfo',
            name='uuidStr',
            field=models.CharField(default='ec3b26a5-c8ea-4a83-adc4-67dbb5e8c4b3', max_length=50),
        ),
    ]
